### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by JonFehl** [Seeed-Studio/Grove_LED_Bar#24]
Problems with esp32

**Comment by JabberwockPL** [comment]
Yes, the examples do not compile for ESP32. Error log attached:

[Error2.txt](https://github.com/Seeed-Studio/Grove_LED_Bar/files/6643886/Error2.txt)

**Comment by michhunger** [comment]
Hi I had the same problem. For me the problem was, that in the Grove_LED_Bar.cpp the min and max functions use default int 0 and 10 as inputs. While they compare with level which is a float. Apparently this is usually automatically casted, but somehow this didnt work. So you have to manually change the code so that everything is casted to a float then it should work. Later in the code they compare with an unsigned char there you have to cast to unsigned char. Hope this helps

**Comment by JabberwockPL** [comment]
Thanks, I will check it out!

**Comment by JabberwockPL** [comment]
This is the same issue and its solution:
https://github.com/AaronLiddiment/LEDSprites/issues/1

**Comment by JabberwockPL** [comment]
Unfortunately, the project compiles, but the module still does not work with ESP32. It runs successfully three or four times and then just stops.
